### ISSUE TITLE
investigate how broken touch/mobile devices are

### ISSUE THREAD

**Issue by matkoniecz** [matkoniecz/lunar_assembler#32]
For start, #1 "UX is poor - user is certainly going to draw a rectangle, step of selecting it manually is pointless" is more severe here

replaces #6

**Comment by Discostu36** [comment]
I should open a pull request but don't have the time right now so I'll just dump the code here:

- [ ] Add to header: ` <meta name="viewport" content="width=device-width, initial-scale=1.0"> `

- [ ]  Remove inline css from #map and svg



- [ ] Add to css file:

``` css
#generated_svg_within {
  width:800px;
  height:600px;
}

#map {
  width:600px;
  height:400px;
  position:relative
}
@media screen and (max-width: 800px) {
  #generated_svg_within {
    width:100% !important;
    height:calc(100vw/8*6) !important;
  }
  
#map {
  width:100%;
  height:calc(100vw/6*4)
}
}
```

- [ ] change svg tag to `<svg height="100%" width="100%" viewBox="0 0 800 600">`
